apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
  namespace: default   # namespace where the cronjob will be deployed
spec:
  schedule: "*/1 * * * *"   # this runs the container every 5 minutes you can change this to any time you want.
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: db-backup
              image: abc_inc/cronjob-server:latest
              command: ["/bin/bash", "-c", "sh ./awesome_backup.sh"]       #command to run when container starts
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: backup-secrets     #secrets stored being passed into the container as environment variables
          restartPolicy: Never